### ISSUE TITLE
bolder menu font on flutterbyexample.com?

### ISSUE THREAD

**Issue by eturk1** [ericwindmill/flutter_by_example_apps#9]
Didn't know how to make a request for the site so...
Terrific site! Can you please use a bolder font for the menu? It's very hard to read:
<img width="469" alt="2018-08-23" src="https://user-images.githubusercontent.com/525280/44564946-7b095e80-a71a-11e8-933d-6ea75aa071db.png">

**Comment by ericwindmill** [comment]
hey @eturk1, I can definitely do that. You can do it too, if you're comfortable making a PR. Otherwise I can get to it this week. Out of curiosity, what browser are you using?

**Comment by eturk1** [comment]
font is thin in chrome, edge, & firefox

and, oh my, I'm not figuring out where the source for the site is. LOL

<img width="344" alt="fbe-firefox" src="https://user-images.githubusercontent.com/525280/44638582-7dfb8d80-a96c-11e8-844c-ab827d672308.png">
<img width="384" alt="fbe-edge" src="https://user-images.githubusercontent.com/525280/44638583-7dfb8d80-a96c-11e8-90c3-04880f9913b4.png">

**Comment by ericwindmill** [comment]
ah I see. It doesn't appear that way for me, which is why I asked. I'll update it, thanks for bringing it to my attention!

**Comment by eturk1** [comment]
Look like ultralight font is being used. Maybe just light will be visible?

<img width="275" alt="2018-08-28" src="https://user-images.githubusercontent.com/525280/44763266-4f61ec00-aaff-11e8-9d53-2e8f044ad9f2.png">

**Comment by ericwindmill** [comment]
This is done

**Comment by eturk1** [comment]
right on! I can read it easily now

<img width="585" alt="2018-10-22 2" src="https://user-images.githubusercontent.com/525280/47320369-1a0ce280-d606-11e8-8383-a4df6969af60.png">
